### ISSUE TITLE
Deadlock in simulation for same config

### ISSUE THREAD

**Issue by JaafarRammal** [SOMAS2021/SOMAS2021#116]
Not sure if deadlock is the correct terminology here, but at the reshuffling stage, for 1 in 20 runs for the same config, the simulation lags forever. Below are the logs for two succeeding runs and two failing runs for the following config:

```
{
    "FoodOnPlatform": 100,
    "Team1Agents": 1,
    "Team2Agents": 1,
    "Team3Agents": 1,
    "Team4Agents": 1,
    "Team5Agents": 1,
    "Team6Agents": 1,
    "RandomAgents": 2,
    "AgentHP": 100,
    "AgentsPerFloor": 1,
    "TicksPerFloor": 10,
    "SimDays": 8,
    "ReshuffleDays": 1,
    "maxHP": 100,
    "weakLevel": 10,
    "width": 45,
    "tau": 10,
    "hpReqCToW": 2,
    "hpCritical": 5,
    "maxDayCritical": 3,
    "HPLossBase": 10,
    "HPLossSlope": 0.25
}
```

Succeeding logs:
[good.zip](https://github.com/SOMAS2021/SOMAS2021/files/7777766/good.zip)

Failing logs:
[bad.zip](https://github.com/SOMAS2021/SOMAS2021/files/7777768/bad.zip)

**Comment by jzzheng22** [comment]
Not a deadlock, I think it's an infinite loop in the shuffle function. 

I suspect it's this line:
```
		for remainingVacancies[newFloor] == 0 || newFloor == agent.BaseAgent().floor {
```
