### ISSUE TITLE
Change definition of length of `day`.

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#13]
In `pkg/infra/tower/tower.go`, change `day` to be `day := platformMovePeriod * numOfFloors`.

The length of a day should be dependent on how many floors there are and how much time is spent per floor, rather than the other way around.

In particular, we need to decide how long the platform should spend on each floor.

This is how a day is currently defined: https://github.com/SOMAS2021/SOMAS2021/blob/main/pkg/infra/tower.go#L54-L56
```
	day := 24 * 60
	numOfFloors := t.agentCount / t.agentsPerFloor
	platformMovePeriod := day / numOfFloors // can add min/max
```

I propose changing it to:
```
	platformMovePeriod := SomeConstant
	numOfFloors := t.agentCount / t.agentsPerFloor
        day := platformMovePeriod * numOfFloors
```

There is perhaps further discussion required on how we set the number of floors as well - right now, the agent count needs to be divisible by the number of agents per floor. Perhaps that should also be changed so it's a product rather than a division... but then that gets complicated since we then need a way of deciding how many agents of each type we want

**Comment by JaafarRammal** [comment]
I think we should set params for:

- Floor count
- Time spent on floor by plat
- Agents per floor

Adding frontend label, we can do this whole inputing / parametrization in frontend step 1

**Comment by jzzheng22** [comment]
From meeting: input params: composition of agents, number of agents per floor, time spent per floor.

**Comment by JaafarRammal** [comment]
I might have missed something but I'm not sure what we're doing about cases where `agentsperfloor % agentscount != 0`? Should we not be passing only one of these parameters and then using the property `agentsperfloor % agentscount == 0` combined with `floorCount` to compute the other?

**Comment by jzzheng22** [comment]
So we want to parametrise how many of each type of agent - this will then give us the total number of agents. Given this, we now need to set either how many floors we want to have, or how many agents we want per floor, and then calculate one from the other.

In either case, we need to make sure that either `agentCount % agentsPerFloor == 0` or `agentCount % numberOfFloors == 0`. I don't think there's a way of doing it without at least one division in the entire process.

Personally I think setting number of agents per floor is just slightly nicer - but happy for this to be discussed further.

When we handle the inputs, we'll need to check that the inputs are legal - in this case, making sure that the number of floors (or agents per floor) is a factor of `agentCount`.

**Comment by JaafarRammal** [comment]
Okay, thanks. Since we have `agentsPerFloor = 1` currently, this shouldn't be an issue.
