### ISSUE TITLE
Define Treaty Struct

### ISSUE THREAD

**Issue by Silvertrousers** [SOMAS2021/SOMAS2021#134]
Define a struct called `Treaty` with the following fields:

- `uuid`
- `signature count`
- `duration` time in days that the treaty will last, will be decremented each day
- `condition` - enum of hp, food, floor and other conditions.
- `condition_op` - a comparison operator for numbers
- `condition_amt` - the amount to which the agent's `condition` must be compared
- `request` - what must be done if the treaty condition is fulfilled, for example `eat`, `leaveFood`, `dontEat` ... others can be added
- `request_amt` - if the request is `eat` then this is the amount that must be eaten.

For example you could have a treaty that looks like:
{"iweur", 1, 4 days, hp, >, 5, leaveFood, 2}

This treaty would say:

if agents hp > 5 then
      leave at least 2 food on the platform for the floor below

**Comment by MattScottEEE** [comment]
Thinking about how this will fit in with handlers, would it be feasible for a base agent function to take in the op code and constraints in order to see if a treaty can be fulfilled?

**Comment by woonmoon** [comment]
This is already being handled in [this branch ](https://github.com/SOMAS2021/SOMAS2021/tree/infra/treaty-messages)

**Comment by MattScottEEE** [comment]
> This is already being handled in [this branch](https://github.com/SOMAS2021/SOMAS2021/tree/infra/treaty-messages)

Might be nice to put the treaty struct inside of util/global types and import it?

**Comment by jzzheng22** [comment]
> > This is already being handled in [this branch](https://github.com/SOMAS2021/SOMAS2021/tree/infra/treaty-messages)
> 
> Might be nice to put the treaty struct inside of util/global types and import it, since baseAgent will need access to this data type

Don't agents import messages already? They would get it from there wouldn't they?

**Comment by MattScottEEE** [comment]
> > > This is already being handled in [this branch](https://github.com/SOMAS2021/SOMAS2021/tree/infra/treaty-messages)
> > 
> > 
> > Might be nice to put the treaty struct inside of util/global types and import it, since baseAgent will need access to this data type
> 
> Don't agents import messages already? They would get it from there wouldn't they?

Yeahhh but as an important data type it might be nice to stick it in utils
