### ISSUE TITLE
Add memory of treaties to baseAgent

### ISSUE THREAD

**Issue by Silvertrousers** [SOMAS2021/SOMAS2021#135]
Add a infinitely sized memory for active treaties called `ActiveTreaties`. 
This will be a map of `string` (a uuid) to `Treaty`.
This will go in baseAgent.

We want to have a few helper functions:

- `AcceptTreaty`
- `DeclineTreaty`
- `FilterExpiredTreaties`

**Comment by jzzheng22** [comment]
re `FilterExpiredTreaties` - not sure if it's necessary at this point?
I've got that handled already here: https://github.com/SOMAS2021/SOMAS2021/commit/12229deb13036f4e99e934aa32f2c5d994405879#commitcomment-62633407
Lines 100 - 101.

Just need to know how it will be added then i can complete it.
