### ISSUE TITLE
Change map of agents to map of pointers to agent struct

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#14]
In `pkg/infra/tower/tower.go`

This should make the setter functions a lot cleaner.

**Comment by udai-arneja** [comment]
The Tower Map of agents is a pointer to base agents, so I guess this is referring to the ABM implementation. See branch infra-abm-compression for changes, I think it's addressing this issue? Could be wrong though.

PR coming after a little more cleanup.

**Comment by jzzheng22** [comment]
Before it was a map of structs, not map of pointers to structs - I'll take a look on Thursday

**Comment by udai-arneja** [comment]
Maybe Gowoon fixed it in the rework hehe. Good luck tomo 😄
