### ISSUE TITLE
Propagation of treaty acceptances

### ISSUE THREAD

**Issue by crsren** [SOMAS2021/SOMAS2021#143]
I think we should allow agents to easily communicate new treaty acceptances with their neighbours (maybe using the statement type messages)...

We currently plan for every treaty to have an integer that counts how many people have previously signed it (the idea being that agents might be more likely to sign a treaty if many other agents are already part of it). 

It would make sense to "communicate back" any treat acceptance to avoid e.g....
1. An agent proposes a treaty to both the neighbour above and below them.
2. The agent below doesn't accept the treaty knowing that only his neighbour is part of it (count = 1)
3. The agent above accepts the treaty and proposes it to their neighbour above. This happens repeatedly until e.g. 10 agents are part of the treaty.
4. The agent that originally proposed the treaty still has count=1. Knowing that actually 10 agents signed up might help him convince the agent below to sign, too. 

_**→ Knowing how many agents actually signed the treaty helps convince new ones to join, so all agents who already signed a treaty benefit from propagating new acceptances back as that only makes the treaty more powerful.**_

**Comment by JaafarRammal** [comment]
This would be an amazing feature. I am not sure myself how this would be implemented, the main reason being that, for example, two agents can have a count of 10 on the same treaty, but it is different agents on each and the actual count is maybe 15, maybe 19, maybe 11.

It could be a message type "TreatyAcceptance" propagating, saying something along the lines "agent X has accept treaty {TREATY_ID}" and then all agents update (if they wish) their local treaty copies

**Comment by jzzheng22** [comment]
I disagree with " we should design all agents to communicate new treaty acceptances with their neighbours". An agent that doesn't want to do this shouldn't be forced to do this. You can add the functionality but the decision to use this would lie with individual agent teams.

**Comment by crsren** [comment]
@JaafarRammal Yessss, good point! Doing this using a counter doesn't work once the agents have been reshuffled, so any treaty with a duration that is longer than the reassignment period would get messy...

Using a TreatyAcceptance message that references the exact agent would solve this and wouldn't be any less efficient than propagating the counter! This also allows agents to have some more complex behaviour based on who is in what treaty rather than a completely anonymous counter...

Similar to the comment in #64 

@jzzheng22 couldn't agree more, it 100% should be up to the agent. Updated the wording

**Comment by jzzheng22** [comment]
You would probably need #150 to solve this issue.

**Comment by jzzheng22** [comment]
Message propagation now works, so if you want to start working on this you should be able to @crsren
