### ISSUE TITLE
Messages need a target floor so agents can communicate across multiple floors

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#150]

**Comment by JaafarRammal** [comment]
I think there is a message that can say "propagate" and it contains another message, cc @Silvertrousers

**Comment by Silvertrousers** [comment]
We don't currently have one it seems, but a propagate can be added.

**Comment by Silvertrousers** [comment]
Seems like a propogate message would be something like:

propogateMessage {
  *baseMessage
  message_to_propogate Message
  targetFloor int
  direction bool // true = up, false = down?
}
