### ISSUE TITLE
Cost associated with Message Passing

### ISSUE THREAD

**Issue by MattScottEEE** [SOMAS2021/SOMAS2021#165]
Possibility of HP decay with message passing to disincentivize screaming 24/7

**Comment by udai-arneja** [comment]
Alternative - limiting the message sending to < X messages a day(some time period)?

**Comment by MattScottEEE** [comment]
> Alternative - limiting the message sending to < X messages a day(some time period)?

Definitely works, but should probably differentiate between message types (assuming we have the shout vs talk), otherwise agents will always shout, compared to having to weigh up the method with the HP drain
