### ISSUE TITLE
Scale maxPlatFood/FoodOnPlatform according to the number of agents in the tower.

### ISSUE THREAD

**Issue by r15hil** [SOMAS2021/SOMAS2021#175]
In the spec it says that everyone should be able to survive (given the right strategies), but this isn't possible as the "FoodOnPlatform" is hard coded as 100 not proportional to number of agents

**Comment by jzzheng22** [comment]
We'll need to scale `maxPlatFood` according to the number of agents in the tower

**Comment by VFjr** [comment]
The solution we came up with is the following (see full discussion in slack thread for this issue in the pull-requests channel)

- Allow FoodOnPlatform, FoodOnPlatformPerAgent and UseFoodPerAgentRatio (or something like that) to be parameters passed to the simulation

- If UseFoodPerAgentRatio is true, then it multiplies FoodOnPlatformPerAgent by number of agents to calculate total food. It ignores the FoodOnPlatform parameter if it is set

- If UseFoodPerAgentRatio is false, then it uses FoodOnPlatform and ignores FoodOnPlatformPerAgent

I will implement this either today or tomorrow. Feel free to comment if anyone has any suggestions.
