### ISSUE TITLE
Change `numOfAgents` in `main.go` to a struct with named fields

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#18]
Currently it's confusing since it uses a slice of ints... and it's hard to tell what number corresponds to what agent type.

Using a struct e.g.

```
type initialAgents struct{
        team1 int
        team2 int
        team3 int
        team4 int
        team5 int
        team6 int
        team7 int
}
```

will be easier to determine how many of each agent we're initialising at the start.

**Comment by udai-arneja** [comment]
Issue will be fixed when the frontend is developed - would require a large change that isn't feasible at this stage.
