### ISSUE TITLE
Let Agent check whether the Platform floor is the same as their own floor

### ISSUE THREAD

**Issue by JeetendraJoshi** [SOMAS2021/SOMAS2021#182]
It would be useful for agent teams to check whether the platform is on their own floor. Agents cannot access a.tower.currPlatFloor so would be highly visible to check this out. We cannot use takeFood(0) as a check as it would return 0 even if the platform is not on your floor.

**Comment by JaafarRammal** [comment]
Good point
Slight correction that currently it returns -1 but it's for any of:
- Not enough food
- Already eaten
- Platform not on floor

```go
func (a *Base) TakeFood(amountOfFood food.FoodType) food.FoodType {
	if amountOfFood == 0 {
		return 0
	}
	if a.floor == a.tower.currPlatFloor && !a.hasEaten && amountOfFood > 0 {
		foodTaken := food.FoodType(math.Min(float64(a.tower.currPlatFood), float64(amountOfFood)))
		a.updateHP(foodTaken)
		a.tower.currPlatFood -= foodTaken
		a.setHasEaten(foodTaken > 0)
		a.Log("An agent has taken food", Fields{"floor": a.floor, "amount": foodTaken})
		return foodTaken
	}
	return -1
}
```
