### ISSUE TITLE
Clean up console prints for backend

### ISSUE THREAD

**Issue by VFjr** [SOMAS2021/SOMAS2021#189]
Well, I accidentally left some prints in my last PR that are not needed, so I'll fix that tomorrow. 

Also there is currently a mix of fmt.Println and log.Println throughout the code. Jaafar suggested to switch everything to log.Println, and also add some new useful prints, such as saying when a simulation started, to what file it was saved, how long did it take, etc

**Comment by JaafarRammal** [comment]
@VFjr FYSA you can now directly do `log.Info()` or `log.Debug()` or `log.Error()` etc... (log is the import name of logrus). That's a preference since it's colored on the console by default!
