### ISSUE TITLE
Incorrectly logged agent death

### ISSUE THREAD

**Issue by r15hil** [SOMAS2021/SOMAS2021#197]
The logged day that an agent dies is when it is reshuffled rather than actual agent death

If we were to print a.Age() at this point it would give the true agent lifespan (closes issue #196)

```
baseagent.go

if a.daysAtCritical >= healthInfo.MaxDayCritical {
        a.Log("Killing agent")
        newHP = 0
}
```

However, for the death.json logs, the day is logged at this point in the code

```
simAgent.go

func (sE *SimEnv) replaceAgents(t *infra.Tower) {
	for uuid, agent := range t.Agents {
		agent := agent.BaseAgent()
		if !agent.IsAlive() {
			delete(t.Agents, uuid)
			sE.stateLog.LogAgentDeath(sE.dayInfo.CurrDay, sE.dayInfo.CurrTick, agent.AgentType())
			sE.Log("An Agent has died", infra.Fields{"agent_type": agent.AgentType().String()})
			t.UpdateDeadAgents(agent.AgentType())
			sE.createNewAgent(t, agent.AgentType(), agent.Floor())
		}
	}
}
```

This gives a lifespan of longer than what it should be.

For example when running for 8 sim days we came across the following output where it logs the agent dying on day 9

![image](https://user-images.githubusercontent.com/48328956/147855922-f067423c-c54f-46a5-b7dc-899ac31d686b.png)

**Comment by JaafarRammal** [comment]
Which one should we remove? Forget about the `sE.stateLog.LogAgentDeath` for now, there is already `sE.Log` in the second function and `a.Log` in the first one. Which one is the correct one?
