### ISSUE TITLE
Surviving Agent Logs

### ISSUE THREAD

**Issue by TeDand** [SOMAS2021/SOMAS2021#218]
Currently, after PR #201 it is possible to see the age at which agents died. For some uses, such as working out the average lifespan of agents, this is not enough information since we do not know how long agents that had not died at the end of the simulation had survived. For this reason, we need to have an additional log at the end of the simulation to show surviving agents and their respective ages. Also another edge case this is needed for is if an agent survives the whole simulation since currently, it will have no logs showing its age.  

We have two suggestions for this:  
- kill all agents at the end of the simulation so that there is a killing log showing the age of the agents at the end of the simulation
- add an extra field in the agent logs every tick showing the age of the agent

**Comment by jzzheng22** [comment]
I would suggest just adding:
```
        sE.Log("Living agents at end of simulation")
        for agentID, agent := range t.Agents {
                agent := agent.BaseAgent()
	        sE.Log(infra.Fields{"agentIDid": agentID, "agentType": agent.AgentType().String(), "agentAge": agent.Age()
        }
```

inside simulation.go

**Comment by jzzheng22** [comment]
Haven't tested to see if that would work etc, but it should roughly work. Feel free to have a go at adding this yourself and making a PR for it - it's a good thing to have.
