### ISSUE TITLE
[APP] Treaty message string description

### ISSUE THREAD

**Issue by JaafarRammal** [SOMAS2021/SOMAS2021#237]
Describe a treaty in a string to visualize on the frontend

**Comment by jzzheng22** [comment]
Use the stringify method I did for messagetype and agenttype ;)

**Comment by JaafarRammal** [comment]
I'm using already for message type and agent type but I can't find one for treaty ://

![image](https://user-images.githubusercontent.com/45538723/148221180-fad243d4-f8fc-4d37-9f77-9576b4c47766.png)

**Comment by mdubied** [comment]
Here are some thoughts from my side:
The amount of information displayed on frontend will probably increase if we add treaties etc. We need this information to analyse the simulation results, but the user might get loss if this amount of information is too large. 
A nice frontend feature to have would be some checkboxes that the user can tick if he/she wants to see the corresponding information. We could have checkboxes for showing message passing, treaty passing, and the basic version would only shows the hp of the agents, their floor and the amount of food they ate (for example).
More specifically for treaties: as a user, I would probably like to track treaties that are proposed or agreed by one specific type of agent. Again, we could have a checkbox for the different agent type or something similar.
I have the feeling that showing every time almost all information we have to the user might be quite overwhelming

**Comment by mdubied** [comment]
The formulation of an accepted treaty on frontend could be something like:
Treaty `id` was concluded between `agent1` and `agent2`: if `condition` `conditionOp` `conditionValue`, then `request` `requestOp` `requestValue` for `duration` days.

**Comment by jzzheng22** [comment]
Treaties would be nice to see represented in a tabular form I think.
I can probably write a `String()` method for `condition`, `request`, `duration`, if you need.

**Comment by JaafarRammal** [comment]
Thanks @mdubied ! On frontend the line in the story would look something like this:

Agent `AGENT_TYPE` proposed treaty `ID` to floor `FLOOR`: if `condition` `conditionOp` `conditionValue`, then `request` `requestOp` `requestValue` for `duration` days`

And then the reply will be yes or no in a separate story line

@jzzheng22 would it be possible to have `String()` for the ones you mentioned? The `String()` method you introduced in other places was very useful actually!

You can also add this treaty proposal sentence above as the overload for the `StoryLog()` function in proposeTreaty in the same PR

**Comment by JaafarRammal** [comment]
Forgot to answer your first comment @mdubied: yes we have filter on roadmap by Friday for the frontend, so you can see the story only for Agent 6 when they're sending AskHP requests

**Comment by jzzheng22** [comment]
> Thanks both!
> 
> @mdubied on frontend the line in the story would look something like this:
> 
> Agent `AGENT_TYPE` proposed treaty `ID` to floor `FLOOR`: if `condition` `conditionOp` `conditionValue`, then `request` `requestOp` `requestValue` for `duration` days`
> 
> And then the reply will be yes or no in a separate story line
> 
> @jzzheng22 would it be possible to have `String()` for the ones you mentioned? The `String()` method you introduced in other places was very useful actually!
> 
> You can also add this treaty proposal sentence above as the overload for the `StoryLog()` function in proposeTreaty in the same PR

Will do so later today. Any other fields you need?

**Comment by JaafarRammal** [comment]
I think that should be good, thanks!
