### ISSUE TITLE
[APP] Add agent utility to the StatsViewer

### ISSUE THREAD

**Issue by daryllimyt** [SOMAS2021/SOMAS2021#257]
I'm moving the main discussion points from slack here, so we don't do any accidental duplicate work

## Motivation
Pitt said in the meeting that he'd like us to be able to show each agent's utility - the issue with that is we don't have a standardised way of measuring this. 

## Approach
Utility calculations should involve the allocation of resources 
Standard utility would be a measure of the food received (each day) out of the total available food.
We have to note that utility is (in essence) similar to a transaction in that we "earn" utility (HP gain due to food) and "spend" utility (HP drain due to messaging / cost of living etc)

This gives 2 baseline approaches to modeling utility:
1. Use total food intake as a fraction of the total food available to it
2. Use "net profit" of utility = `hp gain due to food - hp loss due to CofL/comms/other`

It would make sense to then combine either of these with a mapping (utility function) such as `U(foodIntake) = log(foodIntake)` (at least an increasing, concave function). Ideally we'd have some piecewise/bounded function involving a log or a concave quadratic to account for sensitivity of obtaining further utility at various utility levels. i.e. at lower levels of utility, consuming a unit of food will grant higher utility than if this same unit of food were to be consumed at a higher level.

We would also want to normalize these by the number of deaths, to give an average utility per lifespan metric. 

## Consensus
Ultimately whichever approach we choose doesn't matter, just needs to be standardized over all agents. 
Alternative was to use HP, however it doesn't really consider resource allocation.

## Additional
This doesn't seem to have a use for agents' decision making so it's going to be just for visualization/stats purposes

**Comment by JaafarRammal** [comment]
One way is:
- Implement the utility computation model in the backend
- In base agent, modify the story state to include the utility (you will also have to modify the data struct in the logger)
- In the story state logging function, use the utility variable and add it to the story log for the agent state

The story state doesn't log the agent state every tick, only when a message / death / food change happens, so if you don't want that you can add a logger in the state loggers for the utility and report the utility every tick or every day
