### ISSUE TITLE
Agents can keep taking food in each tick since platform stays for multiple ticks

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#26]
This behaviour is maybe unrealistic - an agent can theoretically take as much food as they like but realistically they will still only be able to eat a limited amount of food before the platform moves on.

We could either limit the amount of food is taken per tick (since they can take food on multiple ticks), or introduce a `HasEaten` field which is set to true after the agent takes as much as food as they want in a single tick, and then they don't take any food on the subsequent ticks.

**Comment by MattScottEEE** [comment]
Could this be handled on the infra side in the form of a 'request for food' ?

This also means that agents won't take food when the platform isn't there, as they can only take food when prompted by the tower.
