### ISSUE TITLE
Agents should know reshuffle days

### ISSUE THREAD

**Issue by JeetendraJoshi** [SOMAS2021/SOMAS2021#260]
Currently, certain agents need to restart states when reshuffling. In the movie, agents also knew when they were going to reshuffle and acted accordingly. For example, sending messages at the end of a day could result in no response after the reshuffle which could result in some problems. Our team was just wondering whether this could be implemented and would think that each agent should know when a reshuffle occurs.

**Comment by jzzheng22** [comment]
(copying here from Slack for completeness)

I'd argue against this - agents can learn the reshuffle period through their experience but I don't think they should be able to access it directly. It's also a known limitation from the current implementation that agents can be reshuffled but end up on the same floor.

See also #77
