### ISSUE TITLE
Move `hpDecay()` to start of day instead of end of day

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#27]
My understanding currently is that `hpDecay()` isn't called until the end of the day - this means that on first day every agent loses HP even if they eat which doesn't make sense.

If an agent's HP is 100, and they eat more than the decay amount of HP, their HP should stay at 100, but from what I can tell it will still decay their HP (since HP is capped at 100).

**Comment by AdrianKoch3010** [comment]
I agree I think ideally, the agent shouldn't directly gain hp when eating food. Rather the hp change should take place whenever the health decay function is called. This is a function of the total food eaten during that day. Therefore, it is fine to call this function at the end of the day (even the first day) as it will only move the agent to a different health class if too little food has been consumed, which is the desired behaviour

**Comment by mdubied** [comment]
With the current implementation, we keep hpDecay at the end of the day but allow the agents to eat more than 100HP,. HP will only be bounded by 100 after hpDecay. So it is possible to stay at 100HP if you start with 100 (as the first day). 
The issue should indeed be solved by PR #62
