### ISSUE TITLE
Create a selfish agent for experimentation

### ISSUE THREAD

**Issue by JaafarRammal** [SOMAS2021/SOMAS2021#34]
Create a selfish agent which:
- Has a selfishness parameter
- Takes an amount of food proportional to its selfishness (can be 0, can be max)

**Comment by MattScottEEE** [comment]
Team6 implements a 'Narcissist' agent (which effectively does the same thing). After the PR has been reviewed we can use this. 

This agent maximises self interest, at the same time minimising collective interest. This is achieved with a narcissism parameter that takes food proportional to its position on the spectrum

**Comment by JaafarRammal** [comment]
Ahh this is amazing @MattScottEEE ! The idea was that alongside the custom agents, we'd inject simple selfish and random agents to "disturb" the system when simulating (e.g. even if all custom agents were ready to collaborate, we'd have a few injected agents that are selfish).

I guess if we're able to expose the narcissism parameter to the simulation parameters, then it is possible to inject a selfish agent alongside your other agent instances.

**Comment by jzzheng22** [comment]
@JaafarRammal  can we close this now?

**Comment by JaafarRammal** [comment]
Is it possible to have that agent separately in the package or is it still undergoing changes? just for state logging purposes to not confused it with their team's agent instances
