### ISSUE TITLE
Message passing: define a common language for agents to use

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#40]
Please add comments with your proposed message struct, as well as what the message is used for/expected behaviour/expected responses etc.

```go
type baseMessage struct {
	senderFloor uint
	responseType Message
}
```

**Comment by jzzheng22** [comment]
Message to say how much food an agent has taken

```
type FoodTakenMessage struct{
        *baseMessage
        foodTaken float64 // Planning to change this to int, see #21 
}
```

**Comment by jzzheng22** [comment]
Message to ask how much food an agent is planning to take

```
type IntendedFoodAmtMsg struct{
        *baseMessage
        foodToTake float64 // Planning to change this to int, see #21 
}
```

**Comment by jzzheng22** [comment]
Message to ask how much food an agent has taken

```
type AskFoodTakenMessage struct{
        *baseMessage
        foodTaken float64 // Planning to change this to int, see #21 
}
```

**Comment by jzzheng22** [comment]
Message to ask an agent's HP

```
type AskHPMessage struct{
        *baseMessage
        hp int
}
```

**Comment by jzzheng22** [comment]
Message to say how much HP an agent has

```
type replyHPMessage struct{
        *baseMessage
        hp int
}
```

**Comment by JaafarRammal** [comment]
Message to tell an agent to leave X amount of food

```golang
type LeaveFoodMessage struct{
        *baseMessage
        food int
}
```

**Comment by JaafarRammal** [comment]
Message to tell an agent to take X amount of food

```go
type TakeFoodMessage struct{
        *baseMessage
        food int
}
```

**Comment by JaafarRammal** [comment]
We can have multiple inheritance levels i.e. a `FoodMessage` struct which has the form

```go
type FoodMessage struct{
        *baseMessage
        food int
}
```

and then food related messages build upon it

**Comment by SaraFFdez** [comment]
Message to ask an agent for their agent ID to form connections

`
type WhoAreYou struct {
*baseMessage
ID string
} 
`

**Comment by SaraFFdez** [comment]
Message to ask an agent for their agent ID to form connections

```go
type WhoAreYou struct {
    *baseMessage
     ID string
} 
```

**Comment by SaraFFdez** [comment]
Response message to send 

```go
type WhoIAm struct {
        *baseMessage
        ID string
} 
```

**Comment by SaraFFdez** [comment]
A response message with a negative connotation, denying collaboration

```go
type Reject struct {
        *baseMessage
        ?
} 
```

**Comment by hussain2603** [comment]
A message to ask how much food is on the platform

`type AskFoodOnPlatMessage struct {
    *baseMessage
    food int
}`

**Comment by hussain2603** [comment]
A message to say how much food is on the platform

```go
type FoodOnPlatMessage struct {
        *baseMessage
        Food int
} 
```
