### ISSUE TITLE
Configure logging such that log files are not huge

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#49]
Could start utilising different logger levels etc

Or just print out debugging info to stdout or something

See #46 for where we first noticed this.

**Comment by lhl2617** [comment]
ive used GH actions for artifacts up to GBs, is that not ok?

**Comment by Silvertrousers** [comment]
Could implement a sampling rate to the logger, combining this with logger levels like -log_tower, -log_agents would allow finer control over this.

**Comment by udai-arneja** [comment]
Started a branch for this : infra-log-compression

**Comment by jzzheng22** [comment]
I don't think is actually an issue worth spending time on
