### ISSUE TITLE
Max number of floors visible for agents

### ISSUE THREAD

**Issue by UMust99** [SOMAS2021/SOMAS2021#50]
I think that the agents should have the information how many floors are in the tower. Or maybe just give the agent the information if it's on the last floor as it would useful for any communication so that the last agent doesn't wait for the answer from the floor below which doesn't exist.

**Comment by jzzheng22** [comment]
I think the only agent that should be able to get the total number of floors in the tower is the agent right at the bottom (and possibly the one above that one). Agents will need to work together to figure out how many floors there are in the tower.

**Comment by Rhys-J** [comment]
I think that the only other floor an agent should be able to see (if any) would be the 1 below. So only the bottom floor agents know the number of floors as each agent knows which floor they are on. 
Personally, I think agents not being able to see any other floors is interesting, as then no agent knows for certain how many floor there are.

**Comment by JaafarRammal** [comment]
First / last agent should know they're on the first / last floor simply because they "can't" communicate with anyone above / below them. Other than that, it would be interesting to add a message asking or revealing how many floors there are in the tower (agents could implement behaviors where they lie about that information)

**Comment by JaafarRammal** [comment]
Thinking about this:
- Agent on floor 1 knows by default there is no one above them (since they know they are on floor 1)
- Agents on floor x != 1 know by default there is someone above them
- We need an information for the agent to know if there is someone under them

Although this being said, I think returning `(Bool, Bool)` for both presence of agent "above" and "below" would make it easier so people don't write their own checker. People would have to write their own state conclusion that `(X, False) -> towerFloors = agent.Floor`

**Comment by Rhys-J** [comment]
From the project specification, its says no-one has ever not reported someone being below them. This is probably just an expression by Pitt (as implementing this is not possible) but I think its something we should consider that agents can't see the floor below them and therefore do not know if they are the bottom floor for certain. They would have to assume it if they received no messages from the floor below.
Maybe, 'line of sight' could be a parameter we explore changing, which would affect how we implement this.

**Comment by JaafarRammal** [comment]
I wrote a function

```go
func (a *Base) SurroundingFloors() (bool, bool) {
	return a.floor != 1, a.floor != a.tower.TotalAgents()/a.tower.agentsPerFloor
}
```

which tells you if there is someone above you or below you. I'm happy with:

> agents can't see the floor below them and therefore do not know if they are the bottom floor for certain

which is something technically independent from "max number of floors". Although it become redundant. There is different levels of exposing information here:

- If you tell an agent the max number of floors and the floor they are one, they automatically deduce `floorCount`, `agentBelow?`, `agentAbove?`, `lastFloor?`
- If you tell an agent the floor they are on, they only deduce `agentAbove?` (which we can even make non-deducible by making the floor count not start at 1, but that's another story)
- If you tell an agent the floor they are on and if there is someone above them or below them, they deduce `agentBelow?`, `agentAbove?`, and only the last agent deduces `lastFloor?` and `floorCount`

I think it's really about what information would we like to expose, and based on that we can change the implementation

**Comment by jzzheng22** [comment]
Might be worth asking tomorrow if the last agent knows they are the last agent?

**Comment by MattScottEEE** [comment]
> First / last agent should know they're on the first / last floor simply because they "can't" communicate with anyone above / below them. Other than that, it would be interesting to add a message asking or revealing how many floors there are in the tower (agents could implement behaviors where they lie about that information)

This shouldn't be allowed as per spec - paraphrasing but "if someone knows how many floors there are, they aren't saying"

**Comment by JaafarRammal** [comment]
Make sense
In that case happy to close the issue and not provide the feature of information about being on first / last floor

**Comment by jzzheng22** [comment]
Just to comment - the agent on the 1st floor would know they're on the first floor.
