### ISSUE TITLE
Reshuffle Agents Before Day 1

### ISSUE THREAD

**Issue by Rhys-J** [SOMAS2021/SOMAS2021#52]
Currently, agents are in a set order on day 1 until the first reshuffle.

The agents in the tower should be randomised from the start.

Not sure if calling reshuffle() before the first day of the simulation would solve this?

**Comment by jzzheng22** [comment]
@udai-arneja @JaafarRammal  Can we make `t.reshuffle()` an exported function? This would make it easy to close this issue.
