### ISSUE TITLE
Log the number of replacements and the agent types that were replaced.

### ISSUE THREAD

**Issue by Rhys-J** [SOMAS2021/SOMAS2021#58]
Will be useful to agent teams to have the number of agents that were replaced tracked in a variable and then outputted at the end of the simulation. 
Maybe at the end of the simulation we output something like total agent replacement number and then list each agent that died by type and which day they died on? (Or how many days they lived but this would require another variable in the agent struct to track I think)

**Comment by MattScottEEE** [comment]
This sounds useful for the vis code (a plot of deaths over time) but perhaps impossible for the agents, due to the lack of involvement from "higher powers." Naturally, agents will know if their neighbours are replaced, but I don't think it's fair to have full knowledge of the tower

**Comment by jzzheng22** [comment]
This info wouldn't be available to the agents - this is for logging only.

**Comment by JaafarRammal** [comment]
I suggest we create a "logging state" for the tower an simulation (if necessary) and have those variables in there, then dump the logging state whenever convenient (during or at the end)
