### ISSUE TITLE
Over-eating behaviour

### ISSUE THREAD

**Issue by r15hil** [SOMAS2021/SOMAS2021#68]
In TakeFood (baseagent.go), we take the min between the amount of food requested vs the amount of food on the platform

`foodTaken := math.Min(a.tower.currPlatFood, amountOfFood)`

we then update the HP, which either goes to 100 or currentHP + foodEaten
`int(math.Min(100, float64(a.hp)+foodTaken))`

We then `a.tower.currPlatFood -= foodTaken`, this means even if our HP updates to 100 rather than currentHP + foodEaten, the excess food from `currentHP + foodEaten` will be removed from the platform.

`a.tower.currPlatFood -= foodTaken`

Is this intended behaviour? i.e over-eating behaviour (you've received max utility so eating more won't change anything)

**Comment by hussain2603** [comment]
yes I think it is intended behaviour

**Comment by MattScottEEE** [comment]
This makes sense - this introduces a concept of complete fullness on top of diminishing returns (ie, whilst we may get reduced hp gain due to overeating when we're weak, it's impossible to gain more than 100% health irrespective of how much you eat)
