### ISSUE TITLE
Implement a function foodNeededToStay(currentHP, HPLevel), foodNeededToLevelUp(currentHP, HPLevel) in baseagent

### ISSUE THREAD

**Issue by mdubied** [SOMAS2021/SOMAS2021#69]
Right now, we have access to `levelWidth`, `HPLevel` etc but not a direct value for the amount of food we need to stay at a given level or to go up one level _knowing the exact currentHP and HPLevel_. The agents would have to compute this information themselves for now.

It would be good to have these 2 functions implemented in `baseagent.go`, so that they are directly available to the agents

**Comment by MattScottEEE** [comment]
Worth doing this once PR #62 is accepted

**Comment by jzzheng22** [comment]
Closed by #167.
