### ISSUE TITLE
Who sent the message

### ISSUE THREAD

**Issue by hussain2603** [SOMAS2021/SOMAS2021#70]
Currently only the message itself is placed in your inbox, but not who sent you the message. So you have no idea where the message actually came from. This means you don't know who to respond to. (unless I'm missing something very obvious?)

I think a simple fix might be placing both the sender floor + the message in the inbox during the SendMessage function in the tower.

**Comment by JaafarRammal** [comment]
Hey! See https://github.com/SOMAS2021/SOMAS2021/blob/main/pkg/messages/baseMessage.go#L9, all messages have a prop indicating the floor they came from

**Comment by jzzheng22** [comment]
Wouldn't you include senderID as well? @JaafarRammal

**Comment by JaafarRammal** [comment]
No, you gotta ask "who dis?" to know who's above you

**Comment by jzzheng22** [comment]
But if you're sending a message wouldn't you know the sender from their voice?

**Comment by hussain2603** [comment]
@jzzheng22 I think senderID is like name right? so you wouldn't know the name of an agent unless they tell you the name right?
