### ISSUE TITLE
Implement the possibility of suicide for the agents

### ISSUE THREAD

**Issue by fds101** [SOMAS2021/SOMAS2021#74]
Currently, agents are able to kill themselves by not eating for a certain amount of time. Would be interesting to make it so they can directly do that if they decide to. In reality something like jumping down the hole in the film. Could be done by forcing the agents HP to go down to zero.

**Comment by MattScottEEE** [comment]
Agents should be self interested and aim to maximise local utility - this means that suicide isn't a possible strategy

**Comment by jzzheng22** [comment]
> Agents should be self interested and aim to maximise local utility - this means that suicide isn't a possible strategy

Closing due to this.
