### ISSUE TITLE
Implement new information for agents.

### ISSUE THREAD

**Issue by SaraFFdez** [SOMAS2021/SOMAS2021#77]
I believe the following information would be useful for agent teams:

- When the day has just started
- When a reshuffling has happened
- The tick in which we just ate (or the platform was on our floor but it was empty so we didn't eat but it would have been our turn)

**Comment by jzzheng22** [comment]
1. I'm not 100% convinced if we should do this - how would an agent know if the day has started in the tower?
2. They would know if a reshuffle happened if their floor is not their previous floor (unless by chance they got reshuffled back to the same floor)
3. I'm not sure what you mean by this one... can you explain more please?

**Comment by SaraFFdez** [comment]
1. In the movie the lights turned off at "night time" and turned on again in the morning so I thought an agent would be able to tell what the new day would be or when the day ends. Since this is when the HP decays as well, in our agent implementation this is something we wanted to take into account. (but can do without if we decide we shouldn´t know this)

2. This is how we currently have it implemented yes, by looking at the floor change, but as you say, if the floor is the same, that would be a problem for my group. Not sure how other people are implementing their agents but it might be beneficial for this to be an easier thing to know

3. In our current implementation my team would need to know when we have eaten. Right now we are checking this by seeing if a.TakeFood() returns a number different than 0, but when you don´t eat anything because the platform is empty, this will still return 0 and the agent cannot know that they have tried to eat (unless I am missing something, please let me know). Is there any way we can know that the platform is on our floor and we tried to eat? If not, it would be nice to implement it 

Thoughts?

**Comment by SaraFFdez** [comment]
For number 3, I propose something like changing the last return of the TakeFood function.

```
func (a *Base) TakeFood(amountOfFood float64) float64 {

       if a.floor == a.tower.currPlatFloor && !a.hasEaten {
		foodTaken := math.Min(a.tower.currPlatFood, amountOfFood)
		a.updateHP(foodTaken)
		a.tower.currPlatFood -= foodTaken
		a.setHasEaten(true)
		a.Log("An agent has taken food", Fields{"floor": a.floor, "amount": foodTaken})
		return foodTaken
	}
	return -1.0 <- Return -1 every time we do not eat so we know that if we have attempted to eat but couldn't, we would return 0
} 
```

Idk if this impacts anything else, but if it doesn't I can implement this and change the TakeFood to an int in the process which has not been closed yet

**Comment by hussain2603** [comment]
For 3. You can see the amount of food on the platform when it comes to your level, so if the amount is 0 then you know you can not eat even if you tried. Would that not work as an implementation?

**Comment by SaraFFdez** [comment]
With some if statements and maths, it could work. But I assume most agent teams will need at least one of the three pieces of information I mentioned for their implementation and it would be useful for them to be of easy access. 

In the case of my team, we want to restart some of our custom variables right after eating. With what I proposed above, our implementation would look something like this:
```
foodTaken := a.TakeFood(x)
if foodTaken != -1{
    //do things
}
```

Using the current food in platform function I still need to check if we have taken any food before, then if it is 0, check if we can see the platform with current platform function (and if we do and it is 0, then do thing) but this will be running every tick and I think there would be easier ways of doing it. 

Similarly, with the other two requests, we can still derive them from some of the functions (unless we are reshuffled to the same floor which would be a problem since we see no floor change and that should be addressed) but it is unnecessarily complicated, especially with so many changes (for example the new Health function or any others to come) and I don't see why these three pieces of info shouldn't be of easy access for all agent teams (as it is info an agent would easily see IRL)

I could be missing something and this be a difficult implementation because I am not fully familiar with the infra code so please let me know if that is the case

**Comment by jzzheng22** [comment]
1. I don't have a strong opinion on this, but @udai-arneja could I get a Team1 perspective?
2. Same case as above. I'm somewhat more against this - maybe an agent just doesn't get reshuffled and doesn't know it. Or we can enforce a reshuffle that means everyone is on a different floor. Again @udai-arneja pinging for your opinion.
3. I'm still not entirely clear what the difference between -1 and 0 would be for `TakeFood()`?

**Comment by SaraFFdez** [comment]
2. For this, IRL I do think an agent would know that others have been reshuffled even if they are in the same cause they would look up and down and see new people, but in code, if they are on the same floor the check for reshuffling would not work and as it stands some agent (ours lol) would malfunction. What you proposed of it not being possible for the agent to end up on the same floor as before reshuffle works perfectly
3. It would just make it easier to identify when we have eaten.

**Comment by jzzheng22** [comment]
Don't have an opinion on 1 and 3, for 2 I think best to ensure reshuffle guarantees a new floor.

**Comment by udai-arneja** [comment]
1. Lets do a poll.
2. Will ensure reshuffle guarantees a new floor.
3. Can do -1 for nothing taken, 0 for 0 requested, and the rest as normal.

**Comment by SaraFFdez** [comment]
Sounds good! Thanks for the changes! We can discuss the first one in one of the meetings :D
