### ISSUE TITLE
Even if you take 0 amount of food you will still not be able to take any other amount of food in the same day

### ISSUE THREAD

**Issue by hussain2603** [SOMAS2021/SOMAS2021#80]
This is minor but I don't think this should happen since you haven't taken any food that day so you should still be able to take certain amount of food in that same day.

This is what the fix could be (unless other things also need to be changed). I can do this quickly if everyone agrees.

```
func (a *Base) TakeFood(amountOfFood float64) float64 {
	if a.floor == a.tower.currPlatFloor && !a.hasEaten && amountOfFood != 0 {
		foodTaken := math.Min(a.tower.currPlatFood, amountOfFood)
		a.updateHP(foodTaken)
		a.tower.currPlatFood -= foodTaken
		a.setHasEaten(true)
		a.Log("An agent has taken food", Fields{"floor": a.floor, "amount": foodTaken})
		return foodTaken
	}
	return 0.0
}
```

**Comment by jzzheng22** [comment]
I think it's probably better to do `a.setHasEaten(foodTaken > 0)`

**Comment by hussain2603** [comment]
> I think it's probably better to do `a.setHasEaten(foodTaken > 0)` rather than add the extra check for `amountOfFood != 0`

yeah that works too. Thanks!
