### ISSUE TITLE
agentType is wrong in `NewBaseAgent`

### ISSUE THREAD

**Issue by jzzheng22** [SOMAS2021/SOMAS2021#91]
`agentType` does not correspond to the team number currently - I'm not sure what the intended behaviour here is. Currently it's an `int` and I don't think it should be an int.

**Comment by udai-arneja** [comment]
Need to decide on how we make new agents. ATM it corresponds to the index of the new agent function, so we instantiate the same agent type that dies. This could be changed to be a random agent type in which case this can be removed. @jzzheng22

**Comment by jzzheng22** [comment]
Might be best to make it an enum rather than index of new agent function... need to think about this some more

**Comment by udai-arneja** [comment]
Tbf probably worth reparameterising the entire thing.

**Comment by jzzheng22** [comment]
https://github.com/SOMAS2021/SOMAS2021/issues/18

Somewhat related to this I think?

**Comment by jzzheng22** [comment]
This can be solved using the solution I've done for message logging in #172

**Comment by jzzheng22** [comment]
FYI @JaafarRammal  @VFjr I'm working on this now, the fix is bigger than I expected - I'll be changing some of the config parameter types etc. to get it to work, but I think it's better this way anyway.

**Comment by VFjr** [comment]
Sure, feel free to change them as you see fit and tag me inside the PR
